pure_pursuit_node:
  ros__parameters:
    waypoints_path: "/home/f1tenth/jonathan_ST/Maps_Racelines/FTM_Halle_Large_Track/FTM_Halle_original_high_res.csv" 
    odom_topic: "/pf/pose/odom"
    car_refFrame: "laser"
    global_refFrame: "map"
    drive_topic: "/drive"
    rviz_waypointselected_topic: "/waypoint_selected"
    
    # Pure Pursuit Parameters
    # Lookahead is computed using the following: lookahead = min(max(min_lookahead, max_lookahead * curr_velocity / lookahead_ratio), max_lookahead); 
    # min_lookahead: 0.5 # for square track
    min_lookahead: 0.6
    max_lookahead: 2.0 # lookahead when the car is going around max velocity
    lookahead_ratio: 4.0 # approximately the max velocity
    # K_p: 0.25 # for square track
    # K_p: 0.22 # for big track
    K_p: 0.22
    steering_limit: 35.0
    velocity_percentage: 0.4 # the limit, can only do 1 lap with clean tires


waypoint_visualiser_node:
  ros__parameters:
    waypoints_path: "/home/f1tenth/jonathan_ST/Maps_Racelines/FTM_Halle_Large_Track/FTM_Halle_original_high_res.csv" 
